#!/bin/bash
# =============================================================================
# @file    helpers
# @brief   Common shell functions used across multiple workflows
# @author  Michael Hucka <mhucka@caltech.edu>
# @license Please see the file named LICENSE in the project directory
# @website https://github.com/caltechlibrary/pubarchiver
#
# The code below assumes the following variables are set by the calling code:
#
# * $log -- the file where a run-time log of actions is written
# * $today -- a string giving today's date
# * $mainscript -- the path to the main workflow script calling these helpers
# * $outputdir -- directory where files from the day's run are written
#
# The code below assumes the existence of the following environment variables:
#
# * EMAIL_FAILURE: email address(es) to send notifications of failures
# * SLACK_CHANNEL: Slack channel to send notifications of failure or success
# * SLACK_CLI_TOKEN: used by slack-cli for the Slack API token
#
# For email delivery via Mailgun API (preferred), also set:
# * MAILGUN_API_KEY: API key for Mailgun service
# * MAILGUN_DOMAIN: domain configured in Mailgun
#
# The code below also assumes that programs "pubarchiver" and "slack" (the
# latter from https://github.com/rockymadden/slack-cli) are on the calling
# user's command search $path.
# =============================================================================

run_pubarchiver() {
    # We have only two cases, Portico and PMC, so this grungy approach is good
    # enough for now.  Future revisions should generalize this, though.
    destination=Portico
    shopt -s nocasematch
    for i in "$@" ; do
        if [[ "$i" == "pmc" ]] ; then
            destination=PMC
            break
        fi
    done
    shopt -u nocasematch

    # Next, make sure we can find pubarchiver. If not, send mail & quit.
    if ! command -v pubarchiver &> /dev/null; then
        body=$(cat <<EOF
This is an error message generated by the process running pubarchiver for
uploading publications to $destination. The process is unable to find the
program "pubarchiver". This indicates either a configuration problem or
a change in the computer system where the process is executed. Manual
intervention is required. Additional information may be found here:

  computer: `hostname`
  directory: $outputdir

This message was produced by $mainscript on `hostname`.
EOF
)
        echo "$body" | run_mail -s "pubarchiver failure $today" $EMAIL_FAILURE
        run_slack chat send --channel $SLACK_CHANNEL --color "#ff0000" \
              --title "Error: unable to upload micropublication.org to $destination" \
              --text "$mainscript on `hostname` cannot find program 'pubarchiver'"
        exit 1
    fi

    # Run pubarchiver with arguments and save output in $log
    count=$(pubarchiver $@ 2>&1 | tee -a $log | grep "Total articles" | cut -d ' ' -f3)

    # If successful, return the num. of articles written, else send mail & quit
    status=$?
    if (($status == 0)); then
        echo $count
    else
        case "$status" in
            1) cause="No network detected" ;;
            2) cause="The user interrupted program execution" ;;
            3) cause="An exception or fatal error occurred during execution" ;;
            *) cause="An unexpected error occurred during execution" ;;
        esac
        body=$(cat <<EOF
This is an error message generated by the process running pubarchiver for
uploading publications to $destination. While doing its work, pubarchiver has
encountered the following error:

   $cause

The attached log file may indicate a reason for the failure. Look at the
bottom the log file to see what was the last action attempted.

Today's upload to $destination has been stopped.
EOF
)
        echo "$body" | run_mail -s "pubarchiver failure $today" -a $log $EMAIL_FAILURE
        run_slack chat send --channel $SLACK_CHANNEL --color "#ff0000" \
              --title "Error: unable to complete $destination archiving for micropublication.org" \
              --text "pubarchiver failed to create archive file for $destination. Cause: $cause."
        run_slack file upload --channels $SLACK_CHANNEL --file $log \
              --comment "Here is the pubarchiver run log:"
        exit $status
    fi
}

run_mail() {
    # Send email via Mailgun API (if configured) or fall back to system mail.
    # Reads email body from stdin and supports the following arguments:
    #   -s SUBJECT   The subject line for the email
    #   -a FILENAME  Attach file to the email (passed as multipart to Mailgun,
    #                or via -a flag to system mail)
    #   RECIPIENT    The email address(es) to send to
    #
    # Priority:
    #   1. If MAILGUN_API_KEY is set, sends via Mailgun API
    #   2. Otherwise, uses system mail command if available
    #   3. If neither available, logs a message and returns silently (exit 0)
    #
    # Environment variables used:
    #   MAILGUN_API_KEY, MAILGUN_DOMAIN (for Mailgun)
    #   $log (file path for logging when mail is unavailable)

    local SUBJECT=""
    local RECIPIENT=""
    local ATTACHMENTS=()
    local BODY

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -s)
                SUBJECT="$2"
                shift 2
                ;;
            -a)
                ATTACHMENTS+=("$2")
                shift 2
                ;;
            *)
                RECIPIENT="$1"
                shift
                ;;
        esac
    done

    # Read email body from stdin
    BODY="$(cat)"

    # Try Mailgun API first (preferred if configured)
    if [[ -n "${MAILGUN_API_KEY:-}" ]]; then
        local curl_args=(
            -sS --fail
            -u "api:${MAILGUN_API_KEY}"
            "https://api.mailgun.net/v3/${MAILGUN_DOMAIN}/messages"
            -F "from=noreply@${MAILGUN_DOMAIN}"
            -F "to=${RECIPIENT}"
            -F "subject=${SUBJECT}"
            -F "text=${BODY}"
        )
        # Add attachments if present (Mailgun API syntax)
        for attachment in "${ATTACHMENTS[@]}"; do
            curl_args+=(-F "attachment=@${attachment}")
        done
        curl "${curl_args[@]}" >/dev/null 2>&1
        return $?
    fi

    # Fall back to system mail
    if command -v mail >/dev/null 2>&1; then
        local mail_cmd="echo \"$BODY\" | mail -s \"$SUBJECT\""
        # Add attachments if present (system mail syntax)
        for attachment in "${ATTACHMENTS[@]}"; do
            mail_cmd+=" -a \"$attachment\""
        done
        mail_cmd+=" \"$RECIPIENT\""
        eval "$mail_cmd"
        return $?
    fi

    # No mail method available; log and return silently
    echo "Unable to send email (mail command not available)" >> $log
    return 0
}

run_slack() {
    # First make sure we can find slack. If not, log it and return silently.
    if ! command -v slack &> /dev/null; then
        echo "Unable to find slack" >> $log
        return
    fi

    # Run slack-cli with arguments. Send its output to /dev/null because it
    # always returns a JSON blob (no way to turn it off) and the resulting
    # output will cause cron to think it should be mailed to the user.
    slack "$@" > /dev/null 2>&1
}

run_curl() {
    # FIXME: this is a hack, made possible by the fact that we currently only
    # upload to PMC.  If ever we upload to more destinations, this needs to
    # be fixed to determine the destination from the arguments.
    destination=PMC

    # First, make sure we can find curl. If not, send mail & quit.
    if ! command -v curl &> /dev/null; then
        body=$(cat <<EOF
This is an error message generated by the process running pubarchiver for
uploading publications to $destination. The process is unable to find the
program "curl". This indicates either a configuration problem or a
change in the computer system where the process is executed. Manual
intervention is required. Additional information may be found here:

  computer: `hostname`
  directory: $outputdir

This message was produced by $mainscript on `hostname`.
EOF
)
        echo "$body" | run_mail -s "PMC upload process failure $today" $EMAIL_FAILURE
        run_slack chat send --channel $SLACK_CHANNEL --color "#ff0000" \
              --title "Error: unable to upload micropublication.org to $destination" \
              --text "$mainscript on `hostname` cannot find program 'curl'"
        exit 1
    fi

    # Run curl.

    curl -w '%{response_code}' $@ >> $log 2>&1
    status=$?
    if (($status > 0)); then
        # The 2nd-to-last line will have a message from curl.
        problem=$(tail -n 2 $log | head -n 1)
        body=$(cat <<EOF
This is an error message generated by the process running pubarchiver for
uploading publications to $destination. The "curl" command used to upload files to
$destination failed with the following return status:

  $problem

The attached log file may indicate a reason for the failure. Look at the
bottom the log file to see what was the last action attempted.

Today's upload to $destination has been stopped.
EOF
)
        echo "$body" | run_mail -s "PMC upload failure $today" -a $log $EMAIL_FAILURE
        run_slack chat send --channel $SLACK_CHANNEL --color "#ff0000" \
              --title "Error: unable to complete PMC upload for micropublication.org" \
              --text "$mainscript unable to ftp to $destination. Cause: $problem."
        run_slack file upload --channels $SLACK_CHANNEL --file $log \
              --comment "Here is the pubarchiver run log:"
        exit $status
    fi
}
